stages:
  - test
  - static-analysis
  - build

test:
  stage: test
  image: golang:1.17
  script: 
   - go test .
  tags:
   - runner

static-analysis:
 stage: test
 image:
  name: sonarsource/sonar-scanner-cli
  entrypoint: [""]
 variables:
 script:
  - sonar-scanner -Dsonar.projectKey=my_project -Dsonar.sources=. -Dsonar.host.url=http://gitlab.localdomain:9000 -Dsonar.login=sqp_466ae030f0974e06ecfb586f74a85756cdb4e746
 tags:
  - runner

build:
  stage: build
  image: docker:latest
  script:
   - docker build .
  tags:
   - runner
